# Generated by Django 2.2.9 on 2020-01-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappage',
            name='latlng_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
